forge "https://forge.puppetlabs.com"

mod 'puppetlabs-apt', '1.8.0'
mod 'puppetlabs/docker_platform', '1.0.1'
mod 'puppetlabs-stdlib', '4.6.0'
mod 'willdurand/nodejs', '1.8.5'
mod 'garethr/heroku', '0.0.1'
mod 'jamesnetherton/google_chrome', '0.1.0'