forge "https://forge.puppetlabs.com"

mod 'puppetlabs-apt', '2.2.1'
mod 'garethr/docker', '4.1.1'
mod 'puppetlabs-stdlib', '4.9.1'
mod 'counsyl/packer',
  :git => "git://github.com/counsyl/puppet-packer.git",
  :ref => '0.9.18'
